# Generated by Django 5.2 on 2025-06-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomedicaldata',
            name='value',
            field=models.BooleanField(),
        ),
    ]
