# Generated by Django 5.2 on 2025-05-06 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biomedicaldata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='biomedicaldata',
            name='data_file',
            field=models.FileField(upload_to='medical_data/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='biomedicaldata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomedical_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
