# Generated by Django 5.2 on 2025-04-14 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_biomedicaldata_biomedicaldevice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biomedicaldevice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biomedicaldata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.biomedicaldevice'),
        ),
        migrations.DeleteModel(
            name='BiometricData',
        ),
    ]
